// <auto-generated />
using System;
using ContractStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContractStore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ContractStore.Models.People.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BirthName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NamePrefix")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PersonalID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TaxNumber")
                        .HasColumnType("int");

                    b.Property<string>("WornName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BirthDate = new DateTime(1998, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthName = "Bálint",
                            BirthPlace = "Győr",
                            City = "Győr",
                            Email = "balint@gmail.com",
                            FirstName = "Valamilyen",
                            Gender = "Férfi",
                            HouseNumber = 2,
                            LastName = "Bálint",
                            MotherName = "Virág",
                            NamePrefix = "",
                            Nationality = "magyar",
                            PersonalID = 4,
                            PhoneNumber = "0620123456",
                            PostCode = 1234,
                            Street = "Nagy",
                            TaxNumber = 213213,
                            WornName = "Bálint"
                        },
                        new
                        {
                            ID = 2,
                            BirthDate = new DateTime(1996, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthName = "Ádám",
                            BirthPlace = "Győr",
                            City = "Tiszalök",
                            Email = "adam@gmail.com",
                            FirstName = "Valamekkora",
                            Gender = "Férfi",
                            HouseNumber = 3,
                            LastName = "Ádám",
                            MotherName = "Evelin",
                            NamePrefix = "Dr.",
                            Nationality = "német",
                            PersonalID = 6,
                            PhoneNumber = "0620789123",
                            PostCode = 2345,
                            Street = "Kis",
                            TaxNumber = 543453,
                            WornName = "Ádám"
                        },
                        new
                        {
                            ID = 3,
                            BirthDate = new DateTime(1993, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthName = "Zsolt",
                            BirthPlace = "Budapest",
                            City = "Győr",
                            Email = "zsolt@gmail.com",
                            FirstName = "Kovács",
                            Gender = "Férfi",
                            HouseNumber = 26,
                            LastName = "Zsolt",
                            MotherName = "Lilla",
                            NamePrefix = "",
                            Nationality = "magyar",
                            PersonalID = 4,
                            PhoneNumber = "0620123456",
                            PostCode = 1234,
                            Street = "Kovács",
                            TaxNumber = 213213,
                            WornName = "Zsolt"
                        });
                });

            modelBuilder.Entity("ContractStore.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "ricsi@bolya.eu",
                            Name = "Ricsi",
                            PasswordHash = "NJSAj6vUdXexj54gYy+4DYmLpK1JNIno2W6P14JwMtccurNK"
                        });
                });

            modelBuilder.Entity("ContractStore.Models.Vehicle.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Capacity")
                        .HasColumnType("double");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EngineData")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EnvironmentProtectionClass")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("GearBoxType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LicencePlate")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ManuType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Mass")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfStandingPlaces")
                        .HasColumnType("int");

                    b.Property<double>("Performance")
                        .HasColumnType("double");

                    b.Property<DateTime>("PlacedInTrafficDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductYear")
                        .HasColumnType("int");

                    b.Property<string>("ProhibitionOfSelling")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Propellant")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("RateOfPerformance")
                        .HasColumnType("double");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TechnicalValidity")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TractionData")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TransportablePeople")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidityBegin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Capacity = 100.0,
                            Category = "category1",
                            ChassisNumber = "lx123456",
                            Color = "kék",
                            EngineData = "abc122",
                            EngineNumber = "123456678",
                            EnvironmentProtectionClass = "class1",
                            GearBoxType = "automatic",
                            LicencePlate = "abc123",
                            ManuType = "type1",
                            Manufacturer = "bmw",
                            Mass = 1000,
                            NumberOfSeats = 4,
                            NumberOfStandingPlaces = 0,
                            Performance = 1200.0,
                            PlacedInTrafficDate = new DateTime(2018, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductYear = 2014,
                            ProhibitionOfSelling = "yes",
                            Propellant = "no",
                            RateOfPerformance = 98.900000000000006,
                            RegisterDate = new DateTime(2016, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TechnicalValidity = new DateTime(2222, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TractionData = "good",
                            TransportablePeople = 5,
                            ValidityBegin = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "BMW 1"
                        },
                        new
                        {
                            ID = 2,
                            Capacity = 100.0,
                            Category = "category2",
                            ChassisNumber = "lr123456",
                            Color = "piros",
                            EngineData = "abc134",
                            EngineNumber = "123456678",
                            EnvironmentProtectionClass = "class2",
                            GearBoxType = "manual",
                            LicencePlate = "abc444",
                            ManuType = "type2",
                            Manufacturer = "audi",
                            Mass = 1000,
                            NumberOfSeats = 4,
                            NumberOfStandingPlaces = 0,
                            Performance = 1200.0,
                            PlacedInTrafficDate = new DateTime(2018, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductYear = 2014,
                            ProhibitionOfSelling = "yes",
                            Propellant = "no",
                            RateOfPerformance = 98.900000000000006,
                            RegisterDate = new DateTime(2016, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TechnicalValidity = new DateTime(2222, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TractionData = "good",
                            TransportablePeople = 5,
                            ValidityBegin = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "audi 1"
                        },
                        new
                        {
                            ID = 3,
                            Capacity = 100.0,
                            Category = "category3",
                            ChassisNumber = "lj123456",
                            Color = "narancs",
                            EngineData = "abc552",
                            EngineNumber = "123456678",
                            EnvironmentProtectionClass = "class3",
                            GearBoxType = "fél automata",
                            LicencePlate = "abc555",
                            ManuType = "type3",
                            Manufacturer = "mercedes",
                            Mass = 1000,
                            NumberOfSeats = 4,
                            NumberOfStandingPlaces = 0,
                            Performance = 1200.0,
                            PlacedInTrafficDate = new DateTime(2018, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductYear = 2014,
                            ProhibitionOfSelling = "yes",
                            Propellant = "no",
                            RateOfPerformance = 98.900000000000006,
                            RegisterDate = new DateTime(2016, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TechnicalValidity = new DateTime(2222, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TractionData = "good",
                            TransportablePeople = 5,
                            ValidityBegin = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleType = "w12"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
